#!/usr/bin/env bash
# Configures a new Ubuntu server with a HAproxy load-balancer
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get -y install haproxy=1.8.\*
sed -i '/errorfile 504/a listen abenserver' /etc/haproxy/haproxy.cfg
sed -i '/listen abenserver/a \\tbind :80' /etc/haproxy/haproxy.cfg
sed -i '/bind :80/a \\tmode http' /etc/haproxy/haproxy.cfg
sed -i '/mode http/a \\tserver 23298-web-01 44.192.81.96:80 check' /etc/haproxy/haproxy.cfg
sed -i '/server 23298-web-01 44.192.81.96:80 check/a \\tserver 23298-web-02 3.236.224.97:80 check' /etc/haproxy/haproxy.cfg
sed -i '/#EXTRAOPTS="-de -m 16"/a ENABLED=1' /etc/default/haproxy
sudo service haproxy restart
